# Site settings
title: "Murtaza Tamjeed"
email: "tamj786@gmail.com"
url: "https://murtazatamjeed.github.io/"
description: "Murtaza Tamjeed's Personal Website"
keywords: "Murtaza, Tamjeed, UX Researcherr, Inclusive Designer, Accessibility"
skills: "Hello! I’m a Senior UX Researcher and Inclusive Designer with a strong passion for promoting accessibility and fostering inclusion in every digital experience. With a commitment to understanding user needs and advocating for diverse perspectives, I strive to create products and services that are truly user-centric and inclusive. 

</br>
</br>
<p>Please check out my CV for the full details.<p>" 

meta_author: Tamjeed Murtaza

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Murtaza Tamjeed
  location: Location
  social: Around the Web
  # credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/MurtazaTamjeed
  - title: linkedin
    url: https://www.linkedin.com/in/murtaza-tamjeed/
  - title: github
    url: https://github.com/murtazatamjeed
  - title: google
    url: https://scholar.google.com/citations?user=eGq_1IQAAAAJ&hl=en&oi=ao

# Postal address (add as many lines as necessary)
address:
  - line: Rochester
  - line: New York, USA


# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
