# Site settings
title: "About"
email: "tamj786@gmail.com"
url: "https://murtazatamjeed.github.io/"
description: "Murtaza Tamjeed's Personal Website"
keywords: "Murtaza, Tamjeed, UX Researchr, User Experience, Accessibility"
skills: "I’m a Ph.D. student in Computing and Information Sciences at Rochester Institute of Technology, conducting research in HCI and Accessibility, and advised by Dr. Kristen Shinohara. I completed my master’s degree in Software Engineering on the Fulbright program with a focus on engineering accessible software.  
<br /> <br />
My research focuses on designing and developing support tools, including strategies and software solutions that empower researchers with disabilities, in particular computing doctoral students who conduct research in university settings. Meanwhile, I study accessibility in user reviews using machine learning techniques. My current project involves NLP to analyze and automate identification of accessibility user reviews for mobile apps. I also investigate how NLP models are biased toward disability and in predicting and classifying accessibility-related user reviews. 
<br /><br />
I'm also a researcher at the Center for Accessibility and Inclusion Research (CAIR) lab. Currently, interning with Yahoo’s Accessibility and Product Inclusion team. My previous experiences include working with Tetra Tech as a Lead Software Developer, with PAE as Senior Database Specialist and with ADRAS as a Software Developer. 
<br /><br />
Check out my CV for the full details." 


meta_author: Tamjeed Murtaza

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Murtaza Tamjeed
  location: Location
  social: Around the Web
  # credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/MurtazaTamjeed
  - title: linkedin
    url: https://www.linkedin.com/in/murtaza-tamjeed/
  - title: github
    url: https://github.com/murtazatamjeed
  - title: google
    url: https://scholar.google.com/citations?user=eGq_1IQAAAAJ&hl=en&oi=ao

# Postal address (add as many lines as necessary)
address:
  - line: Rochester
  - line: New York, USA


# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
